---
title: "Counter Projection 4 Analyses"
author: "Kathryn Denning"
date: "1/20/2021"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
editor_options: 
  chunk_output_type: console
---

652 participants originally collected from Prolific Academic
3 had empty data lines = 649 in imported dataset

```{r data prep, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
#loading packages
library(foreign)
library(reshape2)
library(tidyverse)
library(dplyr)
library(car)
library(haven)
library(psych)
library(lmerTest)
library(sjPlot)
library(reshape2)
library(data.table)
library(emmeans)
library(effects)
library(Cairo)
library(tinytex)

#making it round to three decimal places
options(scipen = 999)
knitr::opts_knit$set(dev.args = list(type = "cairo"))

#Setting global chunk options
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

#importing the data that has been reviewed for completion of PT task
wide_data <- Import("data_downloaded_January_20_2021.csv") 
```

```{r bot check, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
# Checking if there are any repeat IP addresses that need removed
bot_check  <- wide_data %>% 
  select(sub_id, IPAddress)

#identifying the repeat IP addresses
repeat_ips <- bot_check$IPAddress[duplicated(bot_check$IPAddress)]

# There are none - as expected using Prolific
```

```{r data cleaning}
clean_data <- wide_data %>% 
  # reverse coding items that need reverse coded
  mutate_at(c("selfBFI_1", "selfBFI_7", "selfBFI_3", "selfBFI_8",
              "selfBFI_14", "selfBFI_10", "selfBFI_17", "selfBFI_18",
              "SterBFIAnti_1", "SterBFIAnti_7", "SterBFIAnti_3",
              "SterBFIAnti_8", "SterBFIAnti_14", "SterBFIAnti_10",
              "SterBFIAnti_17", "SterBFIAnti_18", "SterBFITrump_1",
              "SterBFITrump_7", "SterBFITrump_3", "SterBFITrump_8",
              "SterBFITrump_14", "SterBFITrump_10", "SterBFITrump_17",
              "SterBFITrump_18", "TargBFITrump_1", "TargBFITrump_7",
              "TargBFITrump_3", "TargBFITrump_8", "TargBFITrump_14",
              "TargBFITrump_10", "TargBFITrump_17", "TargBFITrump_18",
              "TargBFIAnti_1", "TargBFIAnti_7", "TargBFIAnti_3", 
              "TargBFIAnti_8", "TargBFIAnti_14", "TargBFIAnti_10",
              "TargBFIAnti_17", "TargBFIAnti_18"), 
               list(~dplyr::recode(., `1`= 5, 
                                   `2`= 4, 
                                   `3` = 3, 
                                   `4` = 2, 
                                   `5` = 1))) %>% 
  pivot_longer(c(opin_pol, opin_pol2)) %>% 
  mutate(opin_pol_combined = value) %>% 
  dplyr::select(-value, -name) %>% 
  filter(!is.na(opin_pol_combined)) %>% 
  pivot_longer(c(SterBFIAnti_1:SterBFIAnti_19,
               SterBFITrump_1:SterBFITrump_19,
               TargBFITrump_1:TargBFITrump_19,
               TargBFIAnti_1:TargBFIAnti_19,
               selfBFI_1:selfBFI_19),
               names_sep = "_",
               names_to = c("bfi_type", "BFI_number")) %>% 
  pivot_wider(names_from = bfi_type, values_from = value) %>% 
  pivot_longer(c(TargBFITrump, TargBFIAnti),
              names_to = "BFI_target_group") %>% 
  mutate_at(vars(value), ~replace(., is.na(.), 99)) %>% 
  filter(value != "99") %>% 
  rename(TargBFI = value) %>% 
  mutate(BFI_target_group = (dplyr::recode(BFI_target_group, `TargBFITrump`= "Trump", 
                                   `TargBFIAnti`= "Anti"))) %>% 
  pivot_longer(c(SterEDAnti_1:SterEDAnti_5,
               SterEDTrump_1:SterEDTrump_5,
               TargEDTrump_1:TargEDTrump_5,
               TargEDAnti_1:TargEDAnti_5,
               selfED_1:selfED_5),
               names_sep = "_",
               names_to = c("ed_type", "ED_number")) %>% 
  pivot_wider(names_from = ed_type, values_from = value) %>% 
  pivot_longer(c(TargEDTrump, TargEDAnti),
               names_to = c("ED_targ_group")) %>% 
  mutate_at(vars(value), ~replace(., is.na(.), 99)) %>% 
  filter(value != "99") %>% 
  rename(TargED = value) %>% 
  mutate(ED_targ_group = (dplyr::recode(ED_targ_group, `TargEDTrump`= "Trump", 
                                   `TargEDAnti`= "Anti")),
         ED_number = as.numeric(ED_number),
         BFI_number = as.numeric(BFI_number),
         ED_targ_group = as.factor(ED_targ_group),
         BFI_target_group = as.factor(BFI_target_group),
         opin_pol_combined = as.factor(opin_pol_combined),
         race = as.factor(race),
         gender = as.factor(gender),
         education = as.factor(education),
         parent_education = as.factor(parent_education),
         country_birth = as.factor(country_birth),
         native_language = as.factor(native_language),
         citizen = as.factor(citizen),
         us_location = as.factor(us_location)) %>% 
  select(-c(day_nosupport_targ, day_support_trump_targ, gender_3_TEXT,
            race_8_TEXT, country_birth_2_TEXT, country_raised_2_TEXT,
            native_language_2_TEXT, IPAddress)) %>% 
  mutate(stereoBFI = ifelse(BFI_target_group == "Trump", SterBFITrump,
                             ifelse(BFI_target_group == "Anti", SterBFIAnti, 
                                    NA)),
         stereoED = ifelse(ED_targ_group == "Trump", SterEDTrump,
                           ifelse(ED_targ_group == "Anti", SterEDAnti, NA)),
         contentiousness = ifelse(opin_pol_combined == 1, cont_pol_trump,
                                  ifelse(opin_pol_combined == 2, cont_pol_antitrump, NA)),
         fundaMoral = ifelse(opin_pol_combined == 1, fund_pol_trump,
                                  ifelse(opin_pol_combined == 2, fund_pol_antitrump, NA)),
         polar_lib = ifelse(opin_pol_combined == 1, lib_pol_trump_8,
                                  ifelse(opin_pol_combined == 2, lib_pol_antitrump_8, NA)),
         polar_cons = ifelse(opin_pol_combined == 1, cons_pol_antitrump_8,
                                  ifelse(opin_pol_combined == 2, cons_pol_antitrump_8, NA)),
         threat = ifelse(opin_pol_combined == 1, threat_pol_trump,
                                  ifelse(opin_pol_combined == 2, threat_pol_antitrump, NA)),
         identification = ifelse(opin_pol_combined == 1, ident_pol_trump,
                                  ifelse(opin_pol_combined == 2, ident_pol_antitrump, NA)),
         qcheck_bfi_anti_total = ifelse(qcheck_bfi_notsupport == 2, 1,
                                        ifelse(qcheck2_bfi_notsupport == 2, 1,
                                               ifelse(qcheck_bfi_notsupport == 1, 2, #recoding so 1 = include and 2 = exclude
                                                      ifelse(qcheck_bfi_notsupport == 3, 2, NA)))),
         qcheck_bfi_trump_total = ifelse(qcheck_bfi_trump == 1, 1,
                                         ifelse(qcheck2_bfi_trump == 1, 1,
                                                ifelse(qcheck_bfi_trump == 2, 2,
                                                       ifelse(qcheck_bfi_trump == 3, 2, NA)))),
         qcheck_targ_trump_total = ifelse(qcheck_targ_trump == 1, 1,
                                          ifelse(qcheck2_targ_trump == 1, 1,
                                                 ifelse(qcheck_targ_trump == 2, 2, NA))),
         qcheck_targ_anti_total = ifelse(qcheck_targ_nosupport == 2, 1, #recoding so 1 = include, 2 = exclude
                                         ifelse(qcheck2_targ_nosupport == 2, 1,
                                                ifelse(qcheck_targ_nosupport == 1, 2, NA)))) %>% 
  select(-c(cont_pol_trump, cont_pol_antitrump, fund_pol_trump, 
            fund_pol_antitrump, lib_pol_trump_8, lib_pol_antitrump_8,
            cons_pol_antitrump_8, cons_pol_antitrump_8, threat_pol_trump,
            threat_pol_antitrump, ident_pol_trump, ident_pol_antitrump, consent,
            qcheck_bfi_notsupport, qcheck2_bfi_notsupport, qcheck2_bfi_trump,
            qcheck_bfi_trump, qcheck_targ_trump, qcheck2_targ_trump,
            qcheck_targ_nosupport, qcheck2_targ_nosupport,
            opin_pol_lastchance, cons_pol_trump_8)) %>% 
  filter(qcheck_bfi_anti_total == 1) %>% 
  filter(qcheck_bfi_trump_total == 1) %>% 
  pivot_longer(c(qcheck_targ_trump_total, qcheck_targ_anti_total),
               names_to = c("qcheck_question")) %>% 
  mutate_at(vars(value), ~replace(., is.na(.), 99)) %>% 
  filter(value != "99") %>% 
  filter(value == 1) %>% 
  rename(qcheck_targ = value)

  
#opin_pol: Do you support Trump? 1 = yes; 2 = no; same in follow-up question
# for qcheck not support bfi, 2 is correct; originally
# for qcheck for trump bfi, 1 is correct; originally
# for qcheck for trump targ, 1 is correct; originally
# for qcheck for anti targ, 2 is correct; originally
```
